In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [2]:
df = pd.read_csv('train.csv', index_col=0)
df.head()

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [3]:
df['Type of Travel'] = df['Type of Travel'].map({
    'Personal Travel': 0,
    'Business travel': 1
})
df['Class'] = df['Class'].map({
    'Business': 2,
    'Eco Plus': 1,
    'Eco' : 0
})
df['satisfaction'] = df['satisfaction'].map({
    'neutral or dissatisfied': 0,
    'satisfied': 1
})

In [4]:
df['Arrival Delay in Minutes'] = df['Arrival Delay in Minutes'].fillna(0)

In [16]:
df.head()

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,70172,Male,Loyal Customer,13,0,1,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,0
1,5047,Male,disloyal Customer,25,1,2,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,0
2,110028,Female,Loyal Customer,26,1,2,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,1
3,24026,Female,Loyal Customer,25,1,2,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,0
4,119299,Male,Loyal Customer,61,1,2,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,1

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 24 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   id                                 103904 non-null  int64
 1   Gender                             103904 non-null  str
 2   Customer Type                      103904 non-null  str
 3   Age                                103904 non-null  int64
 4   Type of Travel                     103904 non-null  int64
 5   Class                              103904 non-null  int64
 6   Flight Distance                    103904 non-null  int64
 7   Inflight wifi service              103904 non-null  int64
 8   Departure/Arrival time convenient  103904 non-null  int64
 9   Ease of Online booking             103904 non-null  int64
 10  Gate location                      103904 non-null  int64
 11  Food and drink                     103904 non-null  int64
 12  Online boarding                    103904 non-null  int64
 13  Seat comfort                       103904 non-null  int64
 14  Inflight entertainment             103904 non-null  int64
 15  On-board service                   103904 non-null  int64
 16  Leg room service                   103904 non-null  int64
 17  Baggage handling                   103904 non-null  int64
 18  Checkin service                    103904 non-null  int64
 19  Inflight service                   103904 non-null  int64
 20  Cleanliness                        103904 non-null  int64
 21  Departure Delay in Minutes         103904 non-null  int64
 22  Arrival Delay in Minutes           103904 non-null  float64
 23  satisfaction                       103904 non-null  int64
dtypes: float64(1), int64(21), str(2)
memory usage: 19.0 MB

In [5]:
X = df.drop(['id', 'Customer Type', 'Gender', 'satisfaction'], axis=1)
y= df['satisfaction']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
xgboost = XGBClassifier()
xgboost.fit(X_train, y_train)
y_pred = xgboost.predict(X_test)

In [9]:
print('XGBoost: ')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))

XGBoost:
              precision    recall  f1-score   support

           0       0.95      0.97      0.96     11713
           1       0.96      0.94      0.95      9068

    accuracy                           0.96     20781
   macro avg       0.96      0.95      0.96     20781
weighted avg       0.96      0.96      0.96     20781

[[11398   315]
 [  574  8494]]
0.9572205379914345
0.9642411170393915
0.9367004852227614
0.9502712983162723

In [10]:
lgbm = LGBMClassifier()
lgbm.fit(X_train, y_train)
y_pred = lgbm.predict(X_test)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 35957, number of negative: 47166
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001466 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 930
[LightGBM] [Info] Number of data points in the train set: 83123, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.432576 -> initscore=-0.271350
[LightGBM] [Info] Start training from score -0.271350

In [11]:
print('LGBM: ')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))

LGBM:
              precision    recall  f1-score   support

           0       0.95      0.97      0.96     11713
           1       0.97      0.94      0.95      9068

    accuracy                           0.96     20781
   macro avg       0.96      0.95      0.96     20781
weighted avg       0.96      0.96      0.96     20781

[[11416   297]
 [  589  8479]]
0.9573649006303835
0.9661577028258888
0.9350463167181297
0.9503474557274154

In [12]:
decisiontree = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

decisiontree.fit(X_train, y_train)
y_pred = decisiontree.predict(X_test)

In [13]:
print('DecisionTree: ')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))

DecisionTree:
              precision    recall  f1-score   support

           0       0.92      0.91      0.91     11713
           1       0.89      0.89      0.89      9068

    accuracy                           0.90     20781
   macro avg       0.90      0.90      0.90     20781
weighted avg       0.90      0.90      0.90     20781

[[10672  1041]
 [  984  8084]]
0.902555218709398
0.8859178082191781
0.8914865460961623
0.8886934535260814

In [14]:
randomforest = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

randomforest.fit(X_train, y_train)
y_pred = randomforest.predict(X_test)

In [15]:
print('Random Forest: ')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))

Random Forest:
              precision    recall  f1-score   support

           0       0.93      0.94      0.93     11713
           1       0.92      0.91      0.91      9068

    accuracy                           0.92     20781
   macro avg       0.92      0.92      0.92     20781
weighted avg       0.92      0.92      0.92     20781

[[10979   734]
 [  835  8233]]
0.9244983398296521
0.9181443069030891
0.9079179532421703
0.9130024951483227

In [16]:
base_model = DecisionTreeClassifier(max_depth=1)

adaboost = AdaBoostClassifier(
    estimator=base_model,
    n_estimators=100,
    learning_rate=1.0,
    random_state=42
)

adaboost.fit(X_train, y_train)
y_pred = adaboost.predict(X_test)

In [17]:
print('Ada Boost: ')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))

Ada Boost:
              precision    recall  f1-score   support

           0       0.92      0.93      0.92     11713
           1       0.90      0.89      0.90      9068

    accuracy                           0.91     20781
   macro avg       0.91      0.91      0.91     20781
weighted avg       0.91      0.91      0.91     20781

[[10863   850]
 [ 1004  8064]]
0.9107838891294933
0.9046443796275522
0.8892809880899868
0.8968968968968969